Backend receives -p option
semihlab/onnx-connx pull request #34
Opened 2022-03-30 10:40 UTC by semihlab

* backend receives -p option and pass it to connx engine
* -- is not supported in argparse library of python
* python -m onnx_connx.backend -p 1000 [onnx] [input] will run
  the model 1000 times and dump performance report of connx

2022-03-30 10:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tsnlab/onnx-connx?pullRequest=34) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tsnlab/onnx-connx?pullRequest=34) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tsnlab/onnx-connx?pullRequest=34) it.</sub>

2022-03-31 00:30 UTC, tribela requested changes

2022-03-31 00:30 UTC, tribela commented on onnx_connx/backend.py
> +    backend = Backend.prepare(model, **kwargs)
`backend = Backend.prepare(model, out=args.o, loop_count=args.p)` is more readable.
And, having a longer version of flags make code more readable
ie:
```python
parser.add_argument('-p', '--performance', action='store_true', help='performance profiling')
# And use like this
loop_count = parsed.performance
```

2022-03-31 00:30 UTC, tribela commented on onnx_connx/backend_rep.py
> +    def __init__(self, connx_path, model_path, loop_count=0, delete_path=False):
loop_count=None is better while we ignore if 0 is passed.

2022-03-31 01:07 UTC, semihlab commented on onnx_connx/backend.py
> +    backend = Backend.prepare(model, **kwargs)
Two keyword arguments are optional. So we cannot expect will be used by user. If if use "readable" code you suggested, we need to make all the combinations. I'd like to use the default value of class Backend, not argparser. If we use kwargs dynamically, we can use Backend.prepare's default values but if not Backend.prepare's default value is ignored.

2022-03-31 01:11 UTC, tribela commented on onnx_connx/backend.py
> +    backend = Backend.prepare(model, **kwargs)
Agreed.
Could you change `args.o` to `args.output` and `args.p` to `args.performance`?
related to L165-168

2022-03-31 01:24 UTC, tribela approved these changes

2022-03-31 01:25 UTC, tribela commented
Good to go

2022-03-31 23:17 UTC, merged